class PackageInvalidError(ValueError):...
class PackageExistError(ValueError):...
class PackageNotFoundError(ValueError):...
class PackageDuplicateError(ValueError):...
class ExecutionTimedOut(Exception):...
class UnexpectedExecutionError(Exception):...
class InvalidRiCAString(ValueError):...
